              
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: catalogue
          image: roboshop/catalogue:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: catalogue
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
